undo change committed in error

diff --git a/.github/workflows/data-pipeline.yml b/.github/workflows/data-pipeline.yml
--- a/.github/workflows/data-pipeline.yml
+++ b/.github/workflows/data-pipeline.yml
@@ -655,8 +655,11 @@ jobs:
             exit $exit_code
           done
 
-          echo "ETL failed after $max_attempts attempts."
-          exit 2
+          if [ $exit_code -ne 0 ]; then
+            echo "ETL failed after $max_attempts attempts."
+            exit 2
+          fi
+
       # ==============================
       # 10. Create & upload DB backup (used to restore db in review app env)
       # ==============================
